-- Deprecated. Schema lives in supabase/migrations/.
-- New project: npx supabase db push
-- Existing project that already ran this file:
--   npx supabase migration repair --status applied 20260825173332
--   npx supabase db push
